services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: $PUID:$PUID
    group_add:
      # Change this to match your "render" host group id: `getent group render | cut -d: -f3`
      - "110"
    network_mode: "host"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - "${MEDIA_DIR}:/media"
      # - type: bind
      #   source: /path/to/media2
      #   target: /media2
      #   read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      # - type: bind
      #   source: /path/to/fonts
      #   target: /usr/local/share/fonts/custom
      #   read_only: true
    devices:
      - /dev/dri:/dev/dri
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
