services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./data:/root/.ollama
    ports:
      - 11434:11434
volumes:
  ollama:
    external: true
    name: ollama
