services:
  wiki-db:
    container_name: wikijs-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - wiki-db-data:/var/lib/postgresql/data

  wiki:
    container_name: wikijs
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - wiki-db
    environment:
      DB_TYPE: postgres
      DB_HOST: wiki-db
      DB_PORT: 5432
      DB_NAME: wiki
      DB_USER: wikijs
      DB_PASS: "${DB_PASSWORD}"
    restart: unless-stopped
    volumes:
      - ./data:/wiki/storage
    ports:
      - "3000:3000"

volumes:
  wiki-db-data:

networks:
  default:
    external: true
    name: homeserver
